parameters:
  vhost_name: demo.serviredbundle.com
rc_servired:
  clave: qwertyasdf0123456789
  name: TPV Servired Bundle
  code: 327234688 
  terminal: 001
  transactiontype: 0
  url: http://%vhost_name%/demo/done
  provider: https://sis-t.redsys.es:25443/sis/realizarPago
  url_ok: http://%vhost_name%/demo/success
  url_ko: http://%vhost_name%/demo/failed
  paymethod: T
